NumPy is the fundamental package for scientific computing in Python

**Creating an array**

In [ ]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

**Zeros Function**

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Arrange Function**

Creates an array with starting value, stop value & step value

In [ ]:
np.arange(5,20,4)

array([ 5,  9, 13, 17])

**Linspace function**

In [ ]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
np.linspace(5,8,10)

array([5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ])

In [ ]:
np.linspace(2,3,8)

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        ])

**Full function**

Creates a constant array of a number

In [ ]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

**Eye function**

Creates identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Random.rand function**

Creates an array of random values of desired shape passed as parameter

In [ ]:
np.random.rand(3,3)

array([[0.40261011, 0.47049402, 0.78255357],
       [0.48299665, 0.28879473, 0.54163533],
       [0.80193049, 0.86408682, 0.36060616]])

**Multi-dimensional array**

In [ ]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.full((4,3,2),5)

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [ ]:
np.random.rand(4,3,2)

array([[[0.78643917, 0.93206616],
        [0.73543976, 0.83102698],
        [0.07154362, 0.62697992]],

       [[0.78304016, 0.38189552],
        [0.13286252, 0.6404295 ],
        [0.15306068, 0.10157959]],

       [[0.61413033, 0.74700908],
        [0.36048244, 0.20850445],
        [0.43295291, 0.92718687]],

       [[0.16009741, 0.02710389],
        [0.33165521, 0.78338935],
        [0.41985362, 0.02246225]]])

In [ ]:
np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [6, 5, 4]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 5, 4]]])

In [ ]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
np.arange(0,2,1)

array([0, 1])

**Attributes in NumPy Array**

**1. Dimension of NumPy Array**

ndim function

In [ ]:
a = np.array([[5,10,15],[20,25,20]])
print("Array output: \n",a)
print("Dimension ",a.ndim)

Array output: 
 [[ 5 10 15]
 [20 25 20]]
Dimension  2


**2. Shape of NumPy array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print("Array: \n",a)
print("Shape: ",a.shape)
print("Rows: ",a.shape[0])
print("Column: ",a.shape[1])

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Rows:  2
Column:  3


**3. Size of numpy array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print("Size: ",a.size)

Size:  6


**4. Data types of array**

In [ ]:
np.array([1,2,3,4], dtype= np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1.9,2.0,3.5,4.3], dtype= np.int32)

array([1, 2, 3, 4], dtype=int32)

In [ ]:
np.array([1.9,2.0,3.5,4.3], dtype= np.bool_)

array([ True,  True,  True,  True])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[8,5,2],[6,7,3],[1,4,9]])
print(a.shape)
print(a.size)

(6, 3)
18


**Indexing and Slicing**

**1. Indexing-Accessing array values**

In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[0])
print(i[7])

1
8


In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[-1])
print(i[-5])

9
5


**2. Slicing**

In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[:])

[1 2 3 4 5 6 7 8 9]


In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[1:9:2])

[2 4 6 8]


In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[:-1])

[1 2 3 4 5 6 7 8]


In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[-1:])

[9]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:1])

[[1 2 3]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[1:])

[[4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:-2])

[]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:,::-1])

[[3 2 1]
 [6 5 4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:,::1])

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:,:2])

[[1 2]
 [4 5]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[:,:-2:])

[[1]
 [4]]


In [ ]:
a= np.array([1,2,3,4,5,6,7,8,9])
print(a[-1:-9:-2])

[9 7 5 3]


In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [6, 5, 4]]])
print(a[:,1:,2:])

[[[6]]

 [[4]]]


In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [6, 5, 4]]])
print(a[:,-1:,1:])

[[[5 6]]

 [[5 4]]]


**Array Manipulation functions**

**1. Reshaping a Numpy array**

reshape() method

In [ ]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
a = np.array([3,6,9,12,18,24])
print(np.reshape(a,(3,-1)))
print(np.reshape(a,(-1,3)))
print(np.reshape(a,(3,2)))
print(np.reshape(a,(2,3)))

[[ 3  6]
 [ 9 12]
 [18 24]]
[[ 3  6  9]
 [12 18 24]]
[[ 3  6]
 [ 9 12]
 [18 24]]
[[ 3  6  9]
 [12 18 24]]


**2. Flattening  a NumPy array**

flatten() or ravel()

In [ ]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print(a)
print(b)
print(c)
print(a.shape)
print(b.shape)
print(c.shape)

[[1. 1.]
 [1. 1.]]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
(2, 2)
(4,)
(4,)


**3. Transpose of a Numpy array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b= np.transpose(a)
print(a.shape,'\n\n',a)
print(b.shape,'\n\n',b)

(2, 3) 

 [[1 2 3]
 [4 5 6]]
(3, 2) 

 [[1 4]
 [2 5]
 [3 6]]


**4. Append**

In [ ]:
a = np.array([1,2,3,4,5,6])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**5. Insert**

In [ ]:
np.insert(a,2,10)

array([ 1,  2, 10,  3,  4,  5,  6])

**6. Delete**

In [ ]:
np.delete(a,2)

array([1, 2, 4, 5, 6])

**7. Stacking array**

vstack() - vertical

hstack() - horizontal

In [ ]:
a = np.arange(0,5)
b = np.arange(5,10)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[0 1 2 3 4]
[5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


**8. Concatenating N dimensional array**

In [ ]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print(a)
print(b)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[0 1 2 3 4]]
[[5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]


**Mathematical Operations**

**p,q are two arrays**

1. Addition - np.add(p,q)

2. Subtraction - np.subtract(p,q)

3. Multiplication - np.multiply(p,q)

4. Division - np.divide(p,q)

5. Sum - np.sum(p)

6. CumSum - np.cumsum(p)

7. Mean - np.mean(q)

8. Median - np.median(p)

9. Standard Deviation - np.std(p)

10. Min and max values

In [ ]:
a = np.array([[1,6], [4,3]])
#minimum along a column print
print('Min: ',np.min(a,axis=0))
#maximum along a row print
print('Max: ',np.max(a,axis=1))

Min:  [1 3]
Max:  [6 4]


In [ ]:

import numpy as np
gfg = np.array([[2, 3], [4, 5]])
flat_gfg = gfg.flatten()
print(flat_gfg)

[2 3 4 5]


In [ ]:

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("Array : " + str(array))
reshaped = array.reshape((2, 2, 4))
print("Reshaped 3-D Array : ")
print(reshaped)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
